### ISSUE TITLE
Fix link to API in tutorial 

### ISSUE THREAD

**Issue by VarshC** [JuliaHealth/OMOPCDMCohortCreator.jl#19]
![image](https://user-images.githubusercontent.com/49307186/189156314-18d51b68-74b5-4467-a90c-893b79fb2291.png)

The link to the API currently gives a '404 page not found error'. The API itself can be accessed, just not through this link.

**Comment by dublinsubway** [comment]
I can check docs for API links and fix that if maintainers are cool with that.

That's just the link to [API docs](https://juliahealth.org/OMOPCDMCohortCreator.jl/dev/api/), right?

**Comment by dublinsubway** [comment]
Awh, that's surprisingly nice! I'm a total beginner, so don't have to much hope. Thanks for welcoming!

Threw in a PR there, feel free to take a glance whenever you have time. Best of luck!

**Comment by TheCedarPrince** [comment]
Haha, we all start somewhere and I was in your shoes once before so am happy to help! Added a PR review and great start! If you want to keep working on it together, happy to do so! And welcome to Julia land! :wave:

**Comment by TheCedarPrince** [comment]
Done - thanks!
