### ISSUE TITLE
[FEATURE] Add New Function `GetDrugExposureStartDate`

### ISSUE THREAD

**Issue by TheCedarPrince** [JuliaHealth/OMOPCDMCohortCreator.jl#68]
The following code gets the start dates associated with a particular drug exposure:

```julia
function GetDrugExposureStartDate(
    drug_exposure_ids;
    tab = drug_exposure
)

    sql =
        From(tab) |>
        Where(Fun.in(Get.drug_exposure_id, drug_exposure_ids...)) |>
        Select(Get.drug_exposure_id, Get.drug_exposure_start_date) |>
        q -> render(q, dialect=dialect)

    return String(sql)

end

function GetDrugExposureStartDate(
    drug_exposure_ids,
    conn;
    tab = drug_exposure 
)

    df = DBInterface.execute(conn, GetDrugExposureStartDate(drug_exposure_ids; tab=tab)) |> DataFrame

    return df
end
```

I just haven't had the time yet to add this code into CohortCreator as a new feature. Would be nice to add it in. The implementation is exactly the same as PR #59 and requires a bit more documentation, tests, and a dispatch for DataFrames. 

A great issue for beginners and to get started!

**Comment by nitverse** [comment]
Can You Assign it to me?
Or Should I directly raise the PR

**Comment by TheCedarPrince** [comment]
Hey @nitverse -- thanks for your interest and trying out making a new PR! I commented over on the PR; happy to help more with it! Cheers! :deciduous_tree:
